services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluentpdo-php
    volumes:
      - .:/var/www
    networks:
      - fluentpdo-network

  nginx:
    image: nginx:latest
    container_name: fluentpdo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - fluentpdo-network

  mailhog:
    image: mailhog/mailhog
    container_name: fluentpdo-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface web
    networks:
      - fluentpdo-network

  mariadb:
    image: mariadb:10.5
    container_name: fluentpdo-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - fluentpdo-dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - fluentpdo-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: fluentpdo-swagger
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./docs:/docs

networks:
  fluentpdo-network:
    driver: bridge

volumes:
  fluentpdo-dbdata:
